dependencies:
- absl-py==1.3.0
- aiohappyeyeballs==2.4.4
- aiohttp==3.10.11
- aiohttp-cors==0.8.0
- aioredis==2.0.1
- aiosignal==1.3.1
- ale-py==0.7.4
- annotated-types==0.7.0
- antlr4-python3-runtime==4.8
- anyio==4.0.0
- appdirs==1.4.4
- argon2-cffi==23.1.0
- argon2-cffi-bindings==21.2.0
- arrow==1.3.0
- asttokens==2.2.1
- astunparse==1.6.3
- async-lru==2.0.4
- async-timeout==5.0.1
- atari-py==0.2.9
- attrs==22.2.0
- AutoROM==0.4.2
- AutoROM.accept-rom-license==0.6.1
- Babel==2.13.0
- backcall==0.2.0
- backports.zoneinfo==0.2.1
- beautifulsoup4==4.12.2
- bleach==6.1.0
- blessed==1.20.0
- botocore==1.20.112
- brax==0.12.1
- build==1.2.2.post1
- cached-property==1.5.2
- cachetools==5.2.0
- certifi==2025.1.31
- cffi==1.15.1
- charset-normalizer==3.3.0
- chex==0.1.7
- click==8.1.7
- cloudpickle==1.6.0
- cmake==3.26.4
- colorama==0.4.6
- colorful==0.5.6
- comm==0.1.4
- commonmark==0.9.1
- contextlib2==21.6.0
- contourpy==1.0.6
- control==0.9.3.post2
- cycler==0.11.0
- Cython==0.29.33
- d4rl==1.1
- dataclasses==0.6
- debugpy==1.6.4
- decorator==4.4.2
- defusedxml==0.7.1
- diffuser==0.0.0
- diffusionjax==0.1.7
- dill==0.3.6
- distlib==0.3.8
- dm-control==1.0.1
- dm-env==1.6
- dm-tree==0.1.8
- docker==7.1.1.dev18+gdb7f8b8b
- docker-pycreds==0.4.0
- docstring-parser==0.15
- dynamax==0.1.2
- editor==1.6.6
- einops==0.6.1
- entrypoints==0.4
- etils==0.9.0
- exceptiongroup==1.1.0
- executing==1.2.0
- Farama-Notifications==0.0.4
- fasteners==0.15
- fastjsonschema==2.18.1
- fastprogress==1.0.3
- filelock==3.12.2
- Flask==2.2.3
- Flask-Cors==3.0.10
- flatbuffers==23.5.26
- flatten-dict==0.4.2
- flax==0.7.2
- fonttools==4.38.0
- fqdn==1.5.1
- free-mujoco-py==2.1.6
- frozenlist==1.5.0
- fsspec==2023.12.2
- future==0.18.3
- gast==0.4.0
- gitdb==4.0.10
- GitPython==3.1.32
- glfw==1.12.0
- google==3.0.0
- google-api-core==2.24.2
- google-auth==2.15.0
- google-auth-oauthlib==1.0.0
- google-pasta==0.2.0
- googleapis-common-protos==1.57.0
- gpustat==1.1.1
- grpcio==1.70.0
- grpcio-tools==1.47.0
- gym==0.18.3
- gym-notices==0.0.8
- gymnasium==0.29.1
- h5py==3.7.0
- hydra-core==1.1.0
- hydra-ray-launcher==0.1.3
- hydra-submitit-launcher==1.2.0
- idna==3.10
- imageio==2.35.1
- imageio-ffmpeg==0.5.1
- importlib-metadata==6.0.0
- importlib-resources==5.10.2
- improved-diffusion==0.0.0
- iniconfig==1.1.1
- inquirer==3.4.0
- ipykernel==6.19.4
- ipython==8.7.0
- ipython-genutils==0.2.0
- ipywidgets==8.1.1
- isoduration==20.11.0
- itsdangerous==2.1.2
- jax==0.4.13
- jaxlib==0.4.13
- jaxopt==0.8.1
- jaxtyping==0.2.19
- jedi==0.18.2
- Jinja2==3.1.2
- jmespath==0.10.0
- joblib==1.3.1
- json5==0.9.14
- jsonpointer==2.4
- jsonschema==4.19.1
- jsonschema-specifications==2023.7.1
- jupyter==1.0.0
- jupyter_client==7.4.8
- jupyter-console==6.6.3
- jupyter_core==5.1.2
- jupyter-events==0.7.0
- jupyter-lsp==2.2.0
- jupyter_server==2.7.3
- jupyter_server_terminals==0.4.4
- jupyterlab==4.0.7
- jupyterlab-pygments==0.2.2
- jupyterlab_server==2.25.0
- jupyterlab-widgets==3.0.9
- keras==2.13.1
- Keras-Preprocessing==1.1.2
- kiwisolver==1.4.4
- labmaze==1.0.6
- lax==1.0.0
- libclang==14.0.6
- lit==16.0.6
- lockfile==0.12.2
- lxml==4.9.3
- Markdown==3.4.1
- MarkupSafe==2.1.1
- matplotlib==3.5.3
- matplotlib-inline==0.1.6
- mc-bin-client==1.0.1
- mediapy==1.1.9
- mistune==3.0.2
- mjrl==1.0.0
- mjx==0.1.0
- mkl-fft==1.2.0
- mkl-random==1.2.0
- mkl-service==2.3.0
- ml-collections==0.1.1
- ml-dtypes==0.2.0
- monotonic==1.6
- moviepy==1.0.3
- mpmath==1.3.0
- msgpack==1.0.4
- mujoco==2.1.5
- mujoco-mjx==3.2.3
- mujoco-py==2.1.2.14
- multidict==6.1.0
- MyoSuite==2.8.4
- mypy-extensions==1.0.0
- nbclient==0.8.0
- nbconvert==7.9.2
- nbformat==5.9.2
- nest-asyncio==1.5.6
- networkx==3.1
- notebook==7.0.5
- notebook_shim==0.2.3
- numpy==1.22.0
- nvidia-cublas-cu11==11.11.3.6
- nvidia-cublas-cu12==12.1.3.1
- nvidia-cuda-cupti-cu11==11.8.87
- nvidia-cuda-cupti-cu12==12.1.105
- nvidia-cuda-nvcc-cu11==11.8.89
- nvidia-cuda-nvcc-cu12==12.2.140
- nvidia-cuda-nvrtc-cu12==12.1.105
- nvidia-cuda-runtime-cu11==11.8.89
- nvidia-cuda-runtime-cu12==12.1.105
- nvidia-cufft-cu11==10.9.0.58
- nvidia-cufft-cu12==11.0.2.54
- nvidia-curand-cu12==10.3.2.106
- nvidia-cusolver-cu12==11.4.5.107
- nvidia-cusparse-cu12==12.1.0.106
- nvidia-ml-py==12.570.86
- nvidia-nvjitlink-cu12==12.2.140
- nvidia-nvtx-cu12==12.1.105
- oauthlib==3.2.2
- olefile==0.46
- omegaconf==2.1.2
- opencensus==0.11.4
- opencensus-context==0.1.3
- opencv-python==4.8.1.78
- opt-einsum==3.3.0
- optax==0.1.7
- orbax==0.1.7
- orbax-checkpoint==0.2.3
- overrides==7.4.0
- packaging==25.0
- pandas==1.3.5
- pandocfilters==1.5.0
- parso==0.7.1
- patchelf==0.17.2.1
- pathtools==0.1.2
- pexpect==4.8.0
- pickleshare==0.7.5
- Pillow==7.1.2
- pink-noise-rl==2.0.1
- pip==25.0.1
- pipdeptree==2.24.0
- pipenv==2023.12.1
- pkgutil_resolve_name==1.3.10
- platformdirs==4.2.0
- pluggy==1.0.0
- proglog==0.1.10
- prometheus-client==0.17.1
- promise==2.3
- prompt-toolkit==3.0.36
- propcache==0.2.0
- proto-plus==1.26.1
- protobuf==3.20.3
- psutil==5.9.4
- ptyprocess==0.7.0
- pure-eval==0.2.2
- py-spy==0.4.0
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pybullet==3.2.5
- pycparser==2.22
- pycryptodomex==3.18.0
- pydantic==2.10.6
- pydantic_core==2.27.2
- pygame==2.5.2
- pyglet==1.5.15
- Pygments==2.14.0
- PyOpenGL==3.1.6
- pyparsing==2.4.7
- pyproject_hooks==1.2.0
- pyquaternion==0.9.9
- pytest==7.2.0
- python-dateutil==2.8.2
- python-json-logger==2.0.7
- pytinyrenderer==0.0.14
- pytz==2023.3
- PyYAML==6.0.2
- pyzmq==24.0.1
- qtconsole==5.4.4
- QtPy==2.4.0
- ray==1.2.0
- readchar==4.2.1
- redis==5.2.1
- referencing==0.30.2
- remote-plot==1.2.1
- requests==2.32.3
- requests-oauthlib==1.3.1
- rfc3339-validator==0.1.4
- rfc3986-validator==0.1.1
- rich==13.0.0
- rpds-py==0.10.6
- rsa==4.9
- runs==1.2.2
- s3transfer==0.3.7
- scikit-learn==1.0.2
- scipy==1.9.3
- seaborn==0.13.1
- Send2Trash==1.8.2
- sentry-sdk==2.26.1
- setproctitle==1.3.3
- setuptools==57.4.0
- Shimmy==1.3.0
- six==1.16.0
- sk-video==1.1.10
- sklearn==0.0.post5
- smmap==5.0.0
- sniffio==1.3.0
- soupsieve==2.5
- stable-baselines==2.10.2
- stable-baselines3==1.1.0
- stack-data==0.6.2
- submitit==1.5.1
- svgwrite==1.4.3
- sympy==1.12
- tabulate==0.8.10
- tap==0.2
- tcdm==0.1
- tensorboard==2.13.0
- tensorboard-data-server==0.7.2
- tensorboard-plugin-wit==1.8.1
- tensorboardX==2.6
- tensorflow==2.13.1
- tensorflow-datasets==4.8.0
- tensorflow-estimator==2.13.0
- tensorflow-io-gcs-filesystem==0.29.0
- tensorflow-metadata==1.12.0
- tensorflow-probability==0.21.0
- tensorstore==0.1.37
- termcolor==2.3.0
- terminado==0.17.1
- threadpoolctl==3.1.0
- tinycss2==1.2.1
- toml==0.10.2
- tomli==2.0.1
- tonic==0.3.0
- toolz==0.12.0
- torch==1.9.0
- torchaudio==0.9.0a0+33b2469
- torchvision==0.10.0
- tornado==6.2
- tqdm==4.66.1
- traitlets==5.8.0
- trimesh==3.9.35
- typed-argument-parser==1.8.1
- typeguard==4.0.0
- types-python-dateutil==2.8.19.14
- typing_extensions==4.12.2
- typing-inspect==0.9.0
- tzdata==2023.3
- tzlocal==5.2
- uri-template==1.3.0
- urllib3==1.26.18
- virtualenv==20.25.1
- wandb==0.13.9
- warmup==0.2.0
- wcwidth==0.2.5
- webcolors==1.13
- webencodings==0.5.1
- websocket-client==1.6.4
- Werkzeug==2.2.2
- wheel==0.42.0
- widgetsnbextension==4.0.9
- wrapt==1.14.1
- xmod==1.8.1
- yarl==1.15.2
- zipp==3.11.0
